app:
  name: "gin-api-scaffold-v1"
  port: 8080

mysql:
  user: "root"
  password: "YOUR_PASSWORD_HERE"  # <--- 让别人自己填
  host: "mysql_db"
  port: 3306
  dbname: "gin_project"

auth:
  jwt_secret: "CHANGE_THIS_SECRET" # <--- 提醒别人修改