app:
  name: "gin-api-scaffold-v1"
  port: 8080

mysql:
  user: "root"
  password: ""           # ğŸ‘ˆ åˆ«äººç”¨çš„æ—¶å€™å¡«ä»–ä»¬è‡ªå·±çš„ï¼Œè¿™é‡Œç•™ç©º
  host: "127.0.0.1"
  port: 3306
  dbname: "gin_demo"     # ğŸ‘ˆ æ”¹ä¸ªé€šç”¨çš„åå­—ï¼Œåˆ«å« bubble äº†

redis:
  host: "127.0.0.1"      # ğŸ‘ˆ é»˜è®¤å¡«æœ¬åœ°å›ç¯
  port: 6379
  password: ""
  db: 0