app:
  name: "gin-api-scaffold-v1"
  port: 8080

mysql:
  user: "root"
  password: "123456"           # ğŸ‘ˆ åˆ«äººç”¨çš„æ—¶å€™å¡«ä»–ä»¬è‡ªå·±çš„ï¼Œè¿™é‡Œç•™ç©º
  host: "127.0.0.1"
  port: 3306
  dbname: "gin_project"     # ğŸ‘ˆ æ”¹ä¸ªé€šç”¨çš„åå­—ï¼Œåˆ«å« bubble äº†

redis:
  host: "192.168.64.128"      # ğŸ‘ˆ é»˜è®¤å¡«æœ¬åœ°å›ç¯
  port: 6379
  password: ""
  db: 0

# æ–°å¢æ—¥å¿—é…ç½®
log:
  level: "debug"
  filename: "./logs/my-app.log" # å»ºè®®æ”¾åœ¨ logs æ–‡ä»¶å¤¹ä¸‹
  max_size: 10      # æ¯ä¸ªæ–‡ä»¶ 10MB
  max_backups: 5    # ä¿ç•™ 5 ä¸ªæ—§æ–‡ä»¶
  max_age: 30       # ä¿ç•™ 30 å¤©